# Generated by Django 4.0.6 on 2022-07-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.CharField(max_length=75),
        ),
    ]
