# Generated by Django 4.0.6 on 2022-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitee', '0002_alter_profile_gender_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
